/**
 * Machine-readable error codes per rule C6.
 * Frontend code branches on these — never on English message text.
 */
export enum ErrorCode {
  // Auth
  INVALID_OTP = 'INVALID_OTP',
  OTP_EXPIRED = 'OTP_EXPIRED',
  OTP_RATE_LIMITED = 'OTP_RATE_LIMITED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',

  // Worker
  WORKER_NOT_FOUND = 'WORKER_NOT_FOUND',
  WORKER_NOT_VERIFIED = 'WORKER_NOT_VERIFIED',
  WORKER_NOT_AVAILABLE = 'WORKER_NOT_AVAILABLE',

  // Customer
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',

  // Federation / Cooperative
  FEDERATION_NOT_FOUND = 'FEDERATION_NOT_FOUND',
  COOPERATIVE_NOT_FOUND = 'COOPERATIVE_NOT_FOUND',
  CROSS_TENANT_ACCESS = 'CROSS_TENANT_ACCESS',

  // Jobs
  JOB_NOT_FOUND = 'JOB_NOT_FOUND',
  JOB_ALREADY_ASSIGNED = 'JOB_ALREADY_ASSIGNED',
  JOB_NOT_COMPLETABLE = 'JOB_NOT_COMPLETABLE',
  JOB_NOT_PAYABLE = 'JOB_NOT_PAYABLE',

  // Payments
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_ALREADY_PROCESSED = 'PAYMENT_ALREADY_PROCESSED',
  INVALID_WEBHOOK_SIGNATURE = 'INVALID_WEBHOOK_SIGNATURE',

  // General
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  RATE_LIMITED = 'RATE_LIMITED',
}
