/**
 * Shared enums used across web, mobile, and API.
 * Per rule C3: mirrored from backend Prisma enums.
 */

export enum Role {
  FEDERATION_ADMIN = 'FEDERATION_ADMIN',
  SOCIETY_ADMIN = 'SOCIETY_ADMIN',
  WORKER = 'WORKER',
  CUSTOMER = 'CUSTOMER',
}

export enum VerificationStatus {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum JobStatus {
  PENDING = 'PENDING',
  MATCHED = 'MATCHED',
  ACCEPTED = 'ACCEPTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  DISPUTED = 'DISPUTED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum ServiceCategory {
  ELECTRICIAN = 'ELECTRICIAN',
  PLUMBER = 'PLUMBER',
  CLEANER = 'CLEANER',
  CAREGIVER = 'CAREGIVER',
}

export enum RequestType {
  SCHEDULED = 'SCHEDULED',
  EMERGENCY = 'EMERGENCY',
}

export enum ErrorCode {
  INVALID_OTP = 'INVALID_OTP',
  OTP_EXPIRED = 'OTP_EXPIRED',
  OTP_RATE_LIMITED = 'OTP_RATE_LIMITED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  WORKER_NOT_FOUND = 'WORKER_NOT_FOUND',
  WORKER_NOT_VERIFIED = 'WORKER_NOT_VERIFIED',
  WORKER_NOT_AVAILABLE = 'WORKER_NOT_AVAILABLE',
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
  FEDERATION_NOT_FOUND = 'FEDERATION_NOT_FOUND',
  COOPERATIVE_NOT_FOUND = 'COOPERATIVE_NOT_FOUND',
  CROSS_TENANT_ACCESS = 'CROSS_TENANT_ACCESS',
  JOB_NOT_FOUND = 'JOB_NOT_FOUND',
  JOB_ALREADY_ASSIGNED = 'JOB_ALREADY_ASSIGNED',
  JOB_NOT_COMPLETABLE = 'JOB_NOT_COMPLETABLE',
  JOB_NOT_PAYABLE = 'JOB_NOT_PAYABLE',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_ALREADY_PROCESSED = 'PAYMENT_ALREADY_PROCESSED',
  INVALID_WEBHOOK_SIGNATURE = 'INVALID_WEBHOOK_SIGNATURE',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  RATE_LIMITED = 'RATE_LIMITED',
}
