'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type SupportedLanguage = 'en' | 'hi' | 'kn' | 'ta' | 'te' | 'mr' | 'bn' | 'gu';

export interface LanguageInfo {
  code: SupportedLanguage;
  name: string;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageInfo[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳' },
];

const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    'brand.name': 'BharatGig',
    'brand.subtitle': 'Cooperative Marketplace',
    'nav.home': 'Home',
    'nav.services': 'Explore Services',
    'nav.howItWorks': 'How It Works',
    'nav.forWorkers': 'For Workers',
    'nav.forCooperatives': 'For Cooperatives',
    'nav.about': 'About',
    'nav.signIn': 'Sign In',
    'nav.bookService': 'Book Service',
    'nav.roleSwitcher': 'Role Switcher',
    'role.customer': 'Household Member',
    'role.worker': 'Guild Artisan',
    'role.society': 'Society Admin',
    'role.federation': 'Federation Apex',
    'role.admin': 'Super Admin',
    'hero.badge': 'Cooperative-Owned Digital Public Marketplace',
    'hero.title1': 'Fair Wages for Artisans.',
    'hero.title2': 'Trusted Services for Homes.',
    'hero.desc': 'BharatGig eliminates middleman commissions by connecting households directly with certified cooperative guild workers. Governed by registered cooperative societies and state federations.',
    'hero.ctaBook': 'Book a Verified Service',
    'hero.ctaJoin': 'Join as a Guild Worker',
    'stats.payout': 'Direct Worker Payout',
    'stats.workers': 'Verified Artisans',
    'stats.societies': 'Audited Societies',
    'section.tradesTag': 'Essential Home Trades',
    'section.tradesTitle': 'Popular Service Guilds',
    'section.viewAll': 'View all 4 service bands',
    'why.tag': 'Cooperative Advantage',
    'why.title': 'Why Choose BharatGig?',
    'why.desc': 'A public digital good built on cooperative principles of democratic control, fair compensation, and community welfare.',
    'why.card1.title': '100% Wage Protection',
    'why.card1.desc': 'Zero aggregator commission. 100% of the customer payment goes to the artisan and cooperative welfare fund.',
    'why.card2.title': 'Govt NSQF Certified',
    'why.card2.desc': 'Every worker is verified by their local Labour Society and certified under Skill India Digital NSQF standards.',
    'why.card3.title': 'Social Security & Insurance',
    'why.card3.desc': 'Automatic enrollment in accident coverage, healthcare benefits, and pension funds via cooperative federation.',
    'cta.title': 'Ready to experience trusted, fair trade services?',
    'cta.desc': 'Book a verified technician in under 2 minutes or register your society with the state federation.',
    'cta.bookNow': 'Book Now',
    'cta.register': 'Register Cooperative',
    'matching.aiTitle': 'Sahayak AI — Worker Recommendation & Advisor',
    'matching.deterministicBadge': 'Deterministic Scoring Engine',
    'matching.proximity': 'Geospatial Proximity',
    'matching.rating': 'Cooperative Tenure & Rating',
    'matching.certification': 'NSQF Guild Certification',
    'matching.rotation': 'Fair Rotation & Anti-Monopoly Bias',
    'matching.dispatch': 'Dispatch Artisan',
    'matching.verifiedArtisan': 'Verified Cooperative Member',
    'status.verifiedSession': 'Cooperative Verified Session',
    'chat.placeholder': 'Describe the service you need (e.g., "Leaking pipe in kitchen" or "Electrician for circuit breaker")...',
    'chat.send': 'Send',
    'chat.assistantGreeting': 'Namaste! I am Sahayak AI. Tell me what trade or repair service you need, and I will analyze your request using deterministic scoring to match the best cooperative artisan.',
  },
  hi: {
    'brand.name': 'भारतगिग',
    'brand.subtitle': 'सहकारी श्रम बाज़ार',
    'nav.home': 'मुख्य पृष्ठ',
    'nav.services': 'सेवाएं देखें',
    'nav.howItWorks': 'यह कैसे काम करता है',
    'nav.forWorkers': 'कारीगरों के लिए',
    'nav.forCooperatives': 'सहकारी समितियों के लिए',
    'nav.about': 'हमारे बारे में',
    'nav.signIn': 'लॉग इन करें',
    'nav.bookService': 'कारीगर बुक करें',
    'nav.roleSwitcher': 'भूमिका बदलें',
    'role.customer': 'परिवार / उपभोक्ता',
    'role.worker': 'प्रमाणित कारीगर',
    'role.society': 'सोसायटी प्रशासक',
    'role.federation': 'फेडरेशन शीर्ष निकाय',
    'role.admin': 'प्लेटफ़ॉर्म व्यवस्थापक',
    'hero.badge': 'सहकारी स्वामित्व वाला डिजिटल सार्वजनिक बाज़ार',
    'hero.title1': 'कारीगरों के लिए उचित वेतन।',
    'hero.title2': 'घरों के लिए विश्वसनीय सेवाएं।',
    'hero.desc': 'भारतगिग बिचौलियों के कमीशन को खत्म करके परिवारों को सीधे प्रमाणित सहकारी गिल्ड कारीगरों से जोड़ता है। पंजीकृत सहकारी समितियों और राज्य महासंघों द्वारा संचालित।',
    'hero.ctaBook': 'सत्यापित सेवा बुक करें',
    'hero.ctaJoin': 'कारीगर के रूप में जुड़ें',
    'stats.payout': 'कारीगर को सीधा भुगतान',
    'stats.workers': 'सत्यापित कारीगर',
    'stats.societies': 'ऑडिटेड समितियां',
    'section.tradesTag': 'आवश्यक घरेलू सेवाएं',
    'section.tradesTitle': 'लोकप्रिय सेवा गिल्ड',
    'section.viewAll': 'सभी 4 सेवा श्रेणियां देखें',
    'why.tag': 'सहकारी लाभ',
    'why.title': 'भारतगिग क्यों चुनें?',
    'why.desc': 'लोकतांत्रिक नियंत्रण, उचित पारिश्रमिक और सामुदायिक कल्याण के सहकारी सिद्धांतों पर निर्मित सार्वजनिक डिजिटल मंच।',
    'why.card1.title': '100% वेतन सुरक्षा',
    'why.card1.desc': 'शून्य कमीशन। ग्राहक भुगतान का 100% सीधा कारीगर और सहकारी कल्याण कोष में जाता है।',
    'why.card2.title': 'सरकारी NSQF प्रमाणित',
    'why.card2.desc': 'प्रत्येक कारीगर स्थानीय श्रम समिति द्वारा सत्यापित और स्किल इंडिया डिजिटल NSQF मानकों के तहत प्रमाणित है।',
    'why.card3.title': 'सामाजिक सुरक्षा और बीमा',
    'why.card3.desc': 'सहकारी महासंघ के माध्यम से दुर्घटना बीमा, स्वास्थ्य लाभ और पेंशन निधि में स्वतः नामांकन।',
    'cta.title': 'क्या आप विश्वसनीय सहकारी सेवा अनुभव के लिए तैयार हैं?',
    'cta.desc': '2 मिनट में सत्यापित तकनीशियन बुक करें या अपनी समिति को राज्य महासंघ से पंजीकृत करें।',
    'cta.bookNow': 'अभी बुक करें',
    'cta.register': 'समिति पंजीकृत करें',
    'matching.aiTitle': 'सहायक AI — कारीगर अनुशंसा और सलाहकार',
    'matching.deterministicBadge': 'पारदर्शी स्कोरिंग प्रणाली',
    'matching.proximity': 'भौगोलिक निकटता (40%)',
    'matching.rating': 'सहकारी अनुभव और रेटिंग (25%)',
    'matching.certification': 'NSQF कौशल प्रमाणीकरण (20%)',
    'matching.rotation': 'समान अवसर रोटेशन पूर्वाग्रह (15%)',
    'matching.dispatch': 'कारीगर को भेजें',
    'matching.verifiedArtisan': 'सत्यापित सहकारी सदस्य',
    'status.verifiedSession': 'सहकारी सत्यापित सत्र',
    'chat.placeholder': 'अपनी ज़रूरत बताएं (उदा. "रसोई में पाइप लीक हो रहा है" या "बिजली का शॉर्ट सर्किट ठीक करना है")...',
    'chat.send': 'भेजें',
    'chat.assistantGreeting': 'नमस्ते! मैं सहायक AI हूँ। मुझे बताएं कि आपको किस कार्य या मरम्मत की आवश्यकता है, और मैं पारदर्शी स्कोरिंग के आधार पर सर्वश्रेष्ठ सहकारी कारीगर की अनुशंसा करूँगा।',
  },
  kn: {
    'brand.name': 'ಭಾರತಗಿಗ್',
    'brand.subtitle': 'ಸಹಕಾರಿ ಕಾರ್ಮಿಕ ಮಾರುಕಟ್ಟೆ',
    'nav.home': 'ಮುಖಪುಟ',
    'nav.services': 'ಸೇವೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
    'nav.howItWorks': 'ಇದು ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ',
    'nav.forWorkers': 'ಕುಶಲಕರ್ಮಿಗಳಿಗೆ',
    'nav.forCooperatives': 'ಸಹಕಾರ ಸಂಘಗಳಿಗೆ',
    'nav.about': 'ನಮ್ಮ ಬಗ್ಗೆ',
    'nav.signIn': 'ಲಾಗಿನ್ ಮಾಡಿ',
    'nav.bookService': 'ಸೇವೆ ಬುಕ್ ಮಾಡಿ',
    'nav.roleSwitcher': 'ಪಾತ್ರ ಬದಲಾಯಿಸಿ',
    'role.customer': 'ಗ್ರಾಹಕ ಸದಸ್ಯ',
    'role.worker': 'ಶ್ರೇಣಿ ಕುಶಲಕರ್ಮಿ',
    'role.society': 'ಸಂಘದ ಆಡಳಿತಾಧಿಕಾರಿ',
    'role.federation': 'ಮಹಾ ಮಂಡಳ ಅಪೆಕ್ಸ್',
    'role.admin': 'ಮುಖ್ಯ ನಿರ್ವಾಹಕ',
    'hero.badge': 'ಸಹಕಾರಿ ಮಾಲೀಕತ್ವದ ಡಿಜಿಟಲ್ ಸಾರ್ವಜನಿಕ ಮಾರುಕಟ್ಟೆ',
    'hero.title1': 'ಕುಶಲಕರ್ಮಿಗಳಿಗೆ ನ್ಯಾಯಯುತ ಕೂಲಿ.',
    'hero.title2': 'ಮನೆಗಳಿಗೆ ವಿಶ್ವಾಸಾರ್ಹ ಸೇವೆಗಳು.',
    'hero.desc': 'ಭಾರತಗಿಗ್ ಮಧ್ಯವರ್ತಿಗಳ ಕಮಿಷನ್ ರದ್ದುಪಡಿಸಿ, ಮನೆಗಳನ್ನು ನೇರವಾಗಿ ಪ್ರಮಾಣೀಕೃತ ಸಹಕಾರಿ ಗಿಲ್ಡ್ ಕಾರ್ಮಿಕರಿಗೆ ಸಂಪರ್ಕಿಸುತ್ತದೆ. ನೋಂದಾಯಿತ ಸಹಕಾರ ಸಂಘಗಳು ಮತ್ತು ರಾಜ್ಯ ಒಕ್ಕೂಟಗಳಿಂದ ನಿಯಂತ್ರಿಸಲ್ಪಡುತ್ತದೆ.',
    'hero.ctaBook': 'ಪರಿಶೀಲಿತ ಸೇವೆ ಬುಕ್ ಮಾಡಿ',
    'hero.ctaJoin': 'ಕುಶಲಕರ್ಮಿಯಾಗಿ ಸೇರಿ',
    'stats.payout': 'ಕಾರ್ಮಿಕರಿಗೆ 100% ನೇರ ಪಾವತಿ',
    'stats.workers': 'ಪರಿಶೀಲಿತ ಕುಶಲಕರ್ಮಿಗಳು',
    'stats.societies': 'ಆಡಿಟ್ ಆದ ಸಂಘಗಳು',
    'section.tradesTag': 'ಅಗತ್ಯ ಗೃಹ ಸೇವೆಗಳು',
    'section.tradesTitle': 'ಜನಪ್ರಿಯ ಸೇವಾ ಗಿಲ್ಡ್‌ಗಳು',
    'section.viewAll': 'ಎಲ್ಲಾ 4 ಸೇವಾ ವರ್ಗಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    'why.tag': 'ಸಹಕಾರಿ ಪ್ರಯೋಜನ',
    'why.title': 'ಭಾರತಗಿಗ್ ಏಕೆ ಆಯ್ಕೆ ಮಾಡಬೇಕು?',
    'why.desc': 'ಪ್ರಜಾಸತ್ತಾತ್ಮಕ ನಿಯಂತ್ರಣ, ನ್ಯಾಯಯುತ ಪರಿಹಾರ ಮತ್ತು ಸಮುದಾಯ ಕಲ್ಯಾಣದ ಸಹಕಾರಿ ತತ್ವಗಳ ಮೇಲೆ ನಿರ್ಮಿಸಲಾದ ವೇದಿಕೆ.',
    'why.card1.title': '100% ವೇತನ ರಕ್ಷಣೆ',
    'why.card1.desc': 'ಯಾವುದೇ ಕಮಿಷನ್ ಇಲ್ಲ. ಗ್ರಾಹಕರ ಪಾವತಿಯ 100% ಹಣ ನೇರವಾಗಿ ಕುಶಲಕರ್ಮಿ ಮತ್ತು ಸಹಕಾರಿ ಕಲ್ಯಾಣ ನಿಧಿಗೆ ಹೋಗುತ್ತದೆ.',
    'why.card2.title': 'ಸರ್ಕಾರಿ NSQF ಪ್ರಮಾಣೀಕೃತ',
    'why.card2.desc': 'ಪ್ರತಿಯೊಬ್ಬ ಕೆಲಸಗಾರನು ಸ್ಥಳೀಯ ಕಾರ್ಮಿಕ ಸಂಘದಿಂದ ಪರಿಶೀಲಿಸಲ್ಪಟ್ಟಿದ್ದು, ಸ್ಕಿಲ್ ಇಂಡಿಯಾ ಡಿಜಿಟಲ್ NSQF ಅಡಿಯಲ್ಲಿ ಪ್ರಮಾಣೀಕರಿಸಲ್ಪಟ್ಟಿದ್ದಾನೆ.',
    'why.card3.title': 'ಸಾಮಾಜಿಕ ಭದ್ರತೆ ಮತ್ತು ವಿಮೆ',
    'why.card3.desc': 'ಸಹಕಾರಿ ಮಹಾಮಂಡಳದ ಮೂಲಕ ಅಪಘಾತ ವಿಮೆ, ಆರೋಗ್ಯ ಸೌಲಭ್ಯಗಳು ಮತ್ತು ಪಿಂಚಣಿ ನಿಧಿಗಳಲ್ಲಿ ಸ್ವಯಂಚಾಲಿತ ನೋಂದಣಿ.',
    'cta.title': 'ವಿಶ್ವಾಸಾರ್ಹ ಸಹಕಾರಿ ಸೇವೆಯನ್ನು ಪಡೆಯಲು ಸಿದ್ಧರಿದ್ದೀರಾ?',
    'cta.desc': '2 ನಿಮಿಷಗಳಲ್ಲಿ ಪರಿಶೀಲಿತ ತಂತ್ರಜ್ಞರನ್ನು ಬುಕ್ ಮಾಡಿ ಅಥವಾ ನಿಮ್ಮ ಸಂಘವನ್ನು ರಾಜ್ಯ ಮಹಾಮಂಡಳದಲ್ಲಿ ನೋಂದಾಯಿಸಿ.',
    'cta.bookNow': 'ಈಗಲೇ ಬುಕ್ ಮಾಡಿ',
    'cta.register': 'ಸಂಘ ನೋಂದಾಯಿಸಿ',
    'matching.aiTitle': 'ಸಹಾಯಕ್ AI — ಕುಶಲಕರ್ಮಿ ಶಿಫಾರಸು ಮತ್ತು ಸಲಹೆಗಾರ',
    'matching.deterministicBadge': 'ಪಾರದರ್ಶಕ ಸ್ಕೋರಿಂಗ್ ಎಂಜಿನ್',
    'matching.proximity': 'ಭೌಗೋಳಿಕ ಸಾಮೀಪ್ಯ (40%)',
    'matching.rating': 'ಅನುಭವ ಮತ್ತು ರೇಟಿಂಗ್ (25%)',
    'matching.certification': 'NSQF ಪ್ರಮಾಣೀಕರಣ (20%)',
    'matching.rotation': 'ಸಮಾನ ಅವಕಾಶ ಆವರ್ತನ ಪಕ್ಷಪಾತ (15%)',
    'matching.dispatch': 'ಕುಶಲಕರ್ಮಿಯನ್ನು ಕಳುಹಿಸಿ',
    'matching.verifiedArtisan': 'ಪರಿಶೀಲಿತ ಸಹಕಾರಿ ಸದಸ್ಯ',
    'status.verifiedSession': 'ಪರಿಶೀಲಿತ ಸಹಕಾರಿ ಅಧಿವೇಶನ',
    'chat.placeholder': 'ನಿಮಗೆ ಅಗತ್ಯವಿರುವ ಸೇವೆಯನ್ನು ವಿವರಿಸಿ (ಉದಾ: "ಅಡುಗೆಮನೆಯಲ್ಲಿ ನೀರಿನ ಪೈಪ್ ಸೋರಿಕೆ")...',
    'chat.send': 'ಕಳುಹಿಸಿ',
    'chat.assistantGreeting': 'ನಮಸ್ಕಾರ! ನಾನು ಸಹಾಯಕ AI. ನಿಮ್ಮ ಅಗತ್ಯವನ್ನು ನನಗೆ ತಿಳಿಸಿ, ಅತ್ಯುತ್ತಮ ಸಹಕಾರಿ ಕುಶಲಕರ್ಮಿಯನ್ನು ನಾನು ನಿಯೋಜಿಸುತ್ತೇನೆ.',
  },
  ta: {
    'brand.name': 'பாரத்கிக்',
    'brand.subtitle': 'கூட்டுறவு சேவைச் சந்தை',
    'nav.home': 'முகப்பு',
    'nav.services': 'சேவைகளை ஆராய்க',
    'nav.howItWorks': 'எப்படி செயல்படுகிறது',
    'nav.forWorkers': 'தொழிலாளர்களுக்கு',
    'nav.forCooperatives': 'கூட்டுறவு சங்கங்களுக்கு',
    'nav.about': 'எங்களைப் பற்றி',
    'nav.signIn': 'உள்நுழைக',
    'nav.bookService': 'சேவை முன்பதிவு',
    'nav.roleSwitcher': 'பயனர் பங்கு',
    'role.customer': 'வீட்டு உரிமையாளர்',
    'role.worker': 'கூட்டுறவு கலைஞர்',
    'role.society': 'சங்க நிர்வாகி',
    'role.federation': 'மாநில கூட்டமைப்பு',
    'role.admin': 'தலைமை நிர்வாகி',
    'hero.badge': 'கூட்டுறவு உரிமம் பெற்ற டிஜிட்டல் பொது சந்தை',
    'hero.title1': 'தொழிலாளர்களுக்கு நியாயமான ஊதியம்.',
    'hero.title2': 'வீடுகளுக்கு நம்பகமான சேவைகள்.',
    'hero.desc': 'இடைத்தரகர் கமிஷன்களை ஒழித்து, வீடுகளை நேரடியாக சான்றளிக்கப்பட்ட தொழிலாளர்களுடன் பாரத்கிக் இணைக்கிறது.',
    'hero.ctaBook': 'சான்றளிக்கப்பட்ட சேவையை முன்பதிவு செய்க',
    'hero.ctaJoin': 'தொழிலாளராக இணைக',
    'stats.payout': 'தொழிலாளர்களுக்கு நேரடி ஊதியம்',
    'stats.workers': 'சரிபார்க்கப்பட்ட கலைஞர்கள்',
    'stats.societies': 'தணிக்கை செய்யப்பட்ட சங்கங்கள்',
    'section.tradesTag': 'அத்தியாவசிய வீட்டுப் பணிகள்',
    'section.tradesTitle': 'பிரபலமான சேவை சங்கங்கள்',
    'section.viewAll': 'அனைத்து சேவைகளையும் பார்க்க',
    'why.tag': 'கூட்டுறவு நன்மைகள்',
    'why.title': 'பாரத்கிக்கை ஏன் தேர்ந்தெடுக்க வேண்டும்?',
    'why.desc': 'மக்களாட்சி கட்டுப்பாடு மற்றும் நியாயமான ஊதிய கொள்கைகளில் இயங்கும் பொது தளம்.',
    'why.card1.title': '100% ஊதிய பாதுகாப்பு',
    'why.card1.desc': 'ஜீரோ கமிஷன். முழுத் தொகையும் தொழிலாளிக்கும் கூட்டுறவு நல நிதிக்கும் செல்கிறது.',
    'why.card2.title': 'அரசு NSQF சான்றிதழ்',
    'why.card2.desc': 'ஒவ்வொரு தொழிலாளியும் ஸ்கில் இந்தியா டிஜிட்டல் கீழ் சான்றளிக்கப்பட்டவர்.',
    'why.card3.title': 'சமூக பாதுகாப்பு & காப்பீடு',
    'why.card3.desc': 'விபத்துக் காப்பீடு மற்றும் சுகாதார நலன்களில் நேரடி பதிவு.',
    'cta.title': 'நம்பகமான கூட்டுறவு சேவைகளைப் பெறத் தயாரா?',
    'cta.desc': '2 நிமிடங்களில் சரிபார்க்கப்பட்ட தொழிலாளரை முன்பதிவு செய்யுங்கள்.',
    'cta.bookNow': 'இப்போதே முன்பதிவு செய்க',
    'cta.register': 'சங்கத்தைப் பதிவு செய்க',
    'matching.aiTitle': 'சஹாயக் AI — தொழிலாளர் பரிந்துரை அமைப்பு',
    'matching.deterministicBadge': 'வெளிப்படையான மதிப்பீட்டு முறை',
    'matching.proximity': 'புவியியல் அருகாமை (40%)',
    'matching.rating': 'தரம் மற்றும் மதிப்பீடு (25%)',
    'matching.certification': 'NSQF திறன் சான்றிதழ் (20%)',
    'matching.rotation': 'சம வாய்ப்பு சுழற்சி (15%)',
    'matching.dispatch': 'தொழிலாளரை அனுப்புக',
    'matching.verifiedArtisan': 'சரிபார்க்கப்பட்ட உறுப்பினர்',
    'status.verifiedSession': 'பாதுகாப்பான கூட்டுறவு அமர்வு',
    'chat.placeholder': 'உங்களுக்கு தேவையான சேவையை விளக்குக...',
    'chat.send': 'அனுப்புக',
    'chat.assistantGreeting': 'வணக்கம்! நான் சஹாயக் AI. உங்கள் தேவையை கூறுங்கள், சிறந்த கூட்டுறவு கலைஞரை பரிந்துரைக்கிறேன்.',
  },
  te: {
    'brand.name': 'భారత్‌గిగ్',
    'brand.subtitle': 'సహకార సేవా వేదిక',
    'nav.home': 'హోమ్',
    'nav.services': 'సేవలు అన్వేషించండి',
    'nav.howItWorks': 'ఇది ఎలా పనిచేస్తుంది',
    'nav.forWorkers': 'కార్మికుల కోసం',
    'nav.forCooperatives': 'సహకార సంఘాల కోసం',
    'nav.about': 'మా గురించి',
    'nav.signIn': 'లాగిన్ అవ్వండి',
    'nav.bookService': 'సేవను బుక్ చేయండి',
    'nav.roleSwitcher': 'పాత్ర మార్చండి',
    'role.customer': 'గృహ యజమాని',
    'role.worker': 'నైపుణ్య కళాకారుడు',
    'role.society': 'సంఘం అడ్మిన్',
    'role.federation': 'రాష్ట్ర సమాఖ్య',
    'role.admin': 'ప్రధాన నిర్వాహకుడు',
    'hero.badge': 'సహకార యాజమాన్య డిజిటల్ పబ్లిక్ మార్కెట్‌ప్లేస్',
    'hero.title1': 'కార్మికులకు సరైన వేతనం.',
    'hero.title2': 'గృహాలకు నమ్మకమైన సేవలు.',
    'hero.desc': 'మధ్యవర్తుల కమీషన్‌ను తొలగించి, గృహాలను నేరుగా ధృవీకరించబడిన సహకార కార్మికులతో భారత్‌గిగ్ కలుపుతుంది.',
    'hero.ctaBook': 'ధృవీకరించిన సేవను బుక్ చేయండి',
    'hero.ctaJoin': 'కార్మికుడిగా చేరండి',
    'stats.payout': 'కార్మికులకు 100% ప్రత్యక్ష చెల్లింపు',
    'stats.workers': 'ధృవీకరించబడిన కళాకారులు',
    'stats.societies': 'ఆడిట్ చేయబడిన సంఘాలు',
    'section.tradesTag': 'అవసరమైన గృహ సేవలు',
    'section.tradesTitle': 'ప్రసిద్ధ సేవా గిల్డ్‌లు',
    'section.viewAll': 'అన్ని 4 కేటగిరీలను చూడండి',
    'why.tag': 'సహకార ప్రయోజనం',
    'why.title': 'భారత్‌గిగ్‌ను ఎందుకు ఎంచుకోవాలి?',
    'why.desc': 'ప్రజాస్వామిక నియంత్రణ మరియు న్యాయమైన వేతన సూత్రాలపై నిర్మించబడిన ప్రజా వేదిక.',
    'why.card1.title': '100% వేతన రక్షణ',
    'why.card1.desc': 'జీరో కమీషన్. కస్టమర్ చెల్లింపు పూర్తిగా కార్మికుడి సంక్షేమ నిధికి చేరుతుంది.',
    'why.card2.title': 'ప్రభుత్వ NSQF ధృవీకరణ',
    'why.card2.desc': 'ప్రతి కార్మికుడు స్కిల్ ఇండియా డిజిటల్ NSQF ప్రమాణాల ప్రకారం సర్టిఫై చేయబడ్డారు.',
    'why.card3.title': 'సామాజిక భద్రత & బీమా',
    'why.card3.desc': 'ప్రమాద బీమా మరియు ఆరోగ్య ప్రయోజనాలలో స్వయంచాలక నమోదు.',
    'cta.title': 'నమ్మకమైన సహకార సేవలను పొందడానికి సిద్ధంగా ఉన్నారా?',
    'cta.desc': '2 నిమిషాల్లో ధృవీకరించబడిన నిపుణుడిని బుక్ చేయండి.',
    'cta.bookNow': 'ఇప్పుడే బుక్ చేయండి',
    'cta.register': 'సంఘాన్ని నమోదు చేయండి',
    'matching.aiTitle': 'సహాయక్ AI — కార్మికుల సిఫార్సు సలహాదారు',
    'matching.deterministicBadge': 'పారదర్శక స్కోరింగ్ వ్యవస్థ',
    'matching.proximity': 'భౌగోళిక సామీప్యత (40%)',
    'matching.rating': 'అనుభవం & రేటింగ్ (25%)',
    'matching.certification': 'NSQF నైపుణ్య ధృవీకరణ (20%)',
    'matching.rotation': 'సమాన అవకాశ రొటేషన్ (15%)',
    'matching.dispatch': 'కార్మికుడిని కేటాయించండి',
    'matching.verifiedArtisan': 'ధృవీకరించబడిన సభ్యుడు',
    'status.verifiedSession': 'సురక్షిత సహకార సెషన్',
    'chat.placeholder': 'మీకు అవసరమైన సేవను వివరించండి...',
    'chat.send': 'పంపండి',
    'chat.assistantGreeting': 'నమస్కారం! నేను సహాయక్ AI. మీ సేవ అవసరాన్ని నాకు చెప్పండి.',
  },
  mr: {
    'brand.name': 'भारतगिग',
    'brand.subtitle': 'सहकारी श्रम बाजारपेठ',
    'nav.home': 'मुख्यपृष्ठ',
    'nav.services': 'सेवा एक्सप्लोर करा',
    'nav.howItWorks': 'हे कसे कार्य करते',
    'nav.forWorkers': 'कामगारांसाठी',
    'nav.forCooperatives': 'सहकारी संस्थांसाठी',
    'nav.about': 'आमच्याबद्दल',
    'nav.signIn': 'साइन इन करा',
    'nav.bookService': 'सेवा बुक करा',
    'nav.roleSwitcher': 'भूमिका बदला',
    'role.customer': 'घरगुती ग्राहक',
    'role.worker': 'प्रमाणित कारागीर',
    'role.society': 'संस्था प्रशासक',
    'role.federation': 'राज्य फेडरेशन',
    'role.admin': 'मुख्य प्रशासक',
    'hero.badge': 'सहकारी मालकीची डिजिटल सार्वजनिक बाजारपेठ',
    'hero.title1': 'कारागिरांना योग्य मोबदला.',
    'hero.title2': 'घरांसाठी विश्वासार्ह सेवा.',
    'hero.desc': 'दलालांचे कमिशन संपवून भारतगिग थेट प्रमाणित सहकारी कामगारांना ग्राहकांशी जोडते.',
    'hero.ctaBook': 'सत्यापित सेवा बुक करा',
    'hero.ctaJoin': 'कामगार म्हणून सामील व्हा',
    'stats.payout': 'कामगारांना थेट मोबदला',
    'stats.workers': 'सत्यापित कारागीर',
    'stats.societies': 'ऑडिट केलेल्या संस्था',
    'section.tradesTag': 'आवश्यक घरगुती सेवा',
    'section.tradesTitle': 'लोकप्रिय सेवा गिल्ड',
    'section.viewAll': 'सर्व 4 सेवा पहा',
    'why.tag': 'सहकारी फायदा',
    'why.title': 'भारतगिग का निवडावे?',
    'why.desc': 'लोकशाही नियंत्रण आणि निष्पक्ष मोबदल्याच्या सहकारी तत्त्वांवर आधारित व्यासपीठ.',
    'why.card1.title': '100% वेतन संरक्षण',
    'why.card1.desc': 'शून्य कमिशन. ग्राहकांचे १००% पैसे थेट कारागीर आणि कल्याण निधीला मिळतात.',
    'why.card2.title': 'सरकारी NSQF प्रमाणित',
    'why.card2.desc': 'प्रत्येक कामगार स्किल इंडिया डिजिटल NSQF मानकांनुसार प्रमाणित आहे.',
    'why.card3.title': 'सामाजिक सुरक्षा आणि विमा',
    'why.card3.desc': 'अपघात विमा आणि आरोग्य लाभांमध्ये थेट नावनोंदणी.',
    'cta.title': 'विश्वासार्ह सहकारी सेवेचा अनुभव घेण्यास तयार आहात का?',
    'cta.desc': '2 मिनिटांत तंत्रज्ञ बुक करा किंवा तुमची संस्था फेडरेशनमध्ये नोंदणीकृत करा.',
    'cta.bookNow': 'आता बुक करा',
    'cta.register': 'संस्था नोंदणी करा',
    'matching.aiTitle': 'सहायक AI — कामगार शिफारस सल्लागार',
    'matching.deterministicBadge': 'पारदर्शक स्कोअरिंग पद्धत',
    'matching.proximity': 'भौगोलिक समीपता (40%)',
    'matching.rating': 'अनुभव आणि रेटिंग (25%)',
    'matching.certification': 'NSQF कौशल्य प्रमाणपत्र (20%)',
    'matching.rotation': 'समान संधी रोटेशन (15%)',
    'matching.dispatch': 'कारागीर नियुक्त करा',
    'matching.verifiedArtisan': 'सत्यापित सहकारी सदस्य',
    'status.verifiedSession': 'सत्यापित सहकारी सत्र',
    'chat.placeholder': 'तुम्हाला कोणती सेवा हवी आहे ते सांगा...',
    'chat.send': 'पाठवा',
    'chat.assistantGreeting': 'नमस्कार! मी सहायक AI आहे. तुम्हाला कोणत्या दुरुस्तीची आवश्यकता आहे ते सांगा.',
  },
  bn: {
    'brand.name': 'ভারতগিগ',
    'brand.subtitle': 'সমবায় শ্রম বাজার',
    'nav.home': 'হোমপেজ',
    'nav.services': 'পরিষেবা অন্বেষণ করুন',
    'nav.howItWorks': 'এটি কীভাবে কাজ করে',
    'nav.forWorkers': 'শ্রমিকদের জন্য',
    'nav.forCooperatives': 'সমবায় সমিতির জন্য',
    'nav.about': 'আমাদের সম্পর্কে',
    'nav.signIn': 'লগ ইন করুন',
    'nav.bookService': 'পরিষেবা বুক করুন',
    'nav.roleSwitcher': 'ভূমিকা পরিবর্তন',
    'role.customer': 'গৃহস্থ গ্রাহক',
    'role.worker': 'দক্ষ কারিগর',
    'role.society': 'সমিতি প্রশাসক',
    'role.federation': 'ফেডারেশন প্রধান',
    'role.admin': 'সিস্টেম অ্যাডমিন',
    'hero.badge': 'সমবায় মালিকানাধীন ডিজিটাল পাবলিক মার্কেটপ্লেস',
    'hero.title1': 'কারিগরদের জন্য ন্যায্য মজুরি।',
    'hero.title2': 'পরিবারের জন্য বিশ্বস্ত পরিষেবা।',
    'hero.desc': 'ভারতগিগ মধ্যস্বত্বভোগীদের কমিশন দূর করে সরাসরি অনুমোদিত সমবায় কর্মীদের পরিবারের সাথে সংযুক্ত করে।',
    'hero.ctaBook': 'যাচাইকৃত পরিষেবা বুক করুন',
    'hero.ctaJoin': 'শ্রমিক হিসাবে যোগ দিন',
    'stats.payout': 'শ্রমিকদের সরাসরি মজুরি',
    'stats.workers': 'যাচাইকৃত কারিগর',
    'stats.societies': 'নিরীক্ষিত সমবায়',
    'section.tradesTag': 'প্রয়োজনীয় গৃহ পরিষেবা',
    'section.tradesTitle': 'জনপ্রিয় পরিষেবা গিল্ড',
    'section.viewAll': 'সব ৪টি পরিষেবা বিভাগ দেখুন',
    'why.tag': 'সমবায়ের সুবিধা',
    'why.title': 'কেন ভারতগিগ বেছে নেবেন?',
    'why.desc': 'গণতান্ত্রিক নিয়ন্ত্রণ এবং ন্যায্য মজুরির সমবায় নীতির ওপর নির্মিত জনকল্যাণমূলক ডিজিটাল প্ল্যাটফর্ম।',
    'why.card1.title': '১০০% মজুরি সুরক্ষা',
    'why.card1.desc': 'শূন্য কমিশন। গ্রাহকের পেমেন্টের সম্পূর্ণ টাকা সরাসরি কারিগর ও কল্যাণ তহবিলে যায়।',
    'why.card2.title': 'সরকারি NSQF প্রত্যয়িত',
    'why.card2.desc': 'প্রতিটি কর্মী স্কিল ইন্ডিয়া ডিজিটাল NSQF মান অনুযায়ী প্রত্যয়িত।',
    'why.card3.title': 'সামাজিক নিরাপত্তা ও বিমা',
    'why.card3.desc': 'দুর্ঘটনা বিমা ও স্বাস্থ্য সুবিধায় স্বয়ংক্রিয় অন্তর্ভুক্তি।',
    'cta.title': 'বিশ্বস্ত সমবায় পরিষেবার অভিজ্ঞতা নিতে প্রস্তুত?',
    'cta.desc': '২ মিনিটে প্রত্যয়িত টেকনিশিয়ান বুক করুন বা আপনার সমিতি নিবন্ধন করুন।',
    'cta.bookNow': 'এখনই বুক করুন',
    'cta.register': 'সমিতি নিবন্ধন করুন',
    'matching.aiTitle': 'সহায়ক AI — কর্মী সুপারিশ উপদেষ্টা',
    'matching.deterministicBadge': 'স্বচ্ছ স্কোরিং ব্যবস্থা',
    'matching.proximity': 'ভৌগোলিক নৈকট্য (৪০%)',
    'matching.rating': 'অভিজ্ঞতা ও রেটিং (২৫%)',
    'matching.certification': 'NSQF দক্ষতা সনদ (২০%)',
    'matching.rotation': 'সমান সুযোগ আবর্তন (১৫%)',
    'matching.dispatch': 'কারিগর প্রেরণ করুন',
    'matching.verifiedArtisan': 'অনুমোদিত সমবায় সদস্য',
    'status.verifiedSession': 'সুরক্ষিত সমবায় অধিবেশন',
    'chat.placeholder': 'আপনার প্রয়োজনীয় পরিষেবা বর্ণনা করুন...',
    'chat.send': 'পাঠান',
    'chat.assistantGreeting': 'নমস্কার! আমি সহায়ক AI। আপনার কী সাহায্য লাগবে আমাকে বলুন।',
  },
  gu: {
    'brand.name': 'ભારતગીગ',
    'brand.subtitle': 'સહકારી શ્રમ બજાર',
    'nav.home': 'મુખ્ય પૃષ્ઠ',
    'nav.services': 'સેવાઓ જુઓ',
    'nav.howItWorks': 'આ કેવી રીતે કાર્ય કરે છે',
    'nav.forWorkers': 'કારીગરો માટે',
    'nav.forCooperatives': 'સહકારી મંડળીઓ માટે',
    'nav.about': 'અમારા વિશે',
    'nav.signIn': 'સાઇન ઇન કરો',
    'nav.bookService': 'સેવા બુક કરો',
    'nav.roleSwitcher': 'રોલ બદલો',
    'role.customer': 'ઘરગથ્થુ સભ્ય',
    'role.worker': 'કુશળ કારીગર',
    'role.society': 'મંડળી એડમિન',
    'role.federation': 'રાજ્ય ફેડરેશન',
    'role.admin': 'મુખ્ય સંચાલક',
    'hero.badge': 'સહકારી માલિકીનું ડિજિટલ જાહેર બજાર',
    'hero.title1': 'કારીગરો માટે યોગ્ય વેતન.',
    'hero.title2': 'ઘરો માટે વિશ્વસનીય સેવાઓ.',
    'hero.desc': 'વચેટિયાઓના કમિશનને નાબૂદ કરીને ભારતગીગ સીધા પ્રમાણિત સહકારી કારીગરોને પરિવારો સાથે જોડે છે.',
    'hero.ctaBook': 'ચકાસાયેલ સેવા બુક કરો',
    'hero.ctaJoin': 'કારીગર તરીકે જોડાઓ',
    'stats.payout': 'કારીગરોને સીધું વેતન',
    'stats.workers': 'ચકાસાયેલ કારીગરો',
    'stats.societies': 'ઓડિટ થયેલ મંડળીઓ',
    'section.tradesTag': 'આવશ્યક ઘર સેવાઓ',
    'section.tradesTitle': 'લોકપ્રિય સેવા ગિલ્ડ્સ',
    'section.viewAll': 'બધી 4 સેવાઓ જુઓ',
    'why.tag': 'સહકારી ફાયદો',
    'why.title': 'ભારતગીગ શા માટે પસંદ કરવું?',
    'why.desc': 'લોકશાહી નિયંત્રણ અને યોગ્ય વળતરના સહકારી સિદ્ધાંતો પર બનેલ જાહેર ડિજિટલ મંચ.',
    'why.card1.title': '100% વેતન સુરક્ષા',
    'why.card1.desc': 'ઝીરો કમિશન. ગ્રાહકની ચૂકવણીના 100% નાણાં સીધા કારીગર અને કલ્યાણ ભંડોળમાં જાય છે.',
    'why.card2.title': 'સરકારી NSQF પ્રમાણિત',
    'why.card2.desc': 'દરેક કાર્યકર સ્કિલ ઇન્ડિયા ડિજિટલ NSQF ધોરણો હેઠળ પ્રમાણિત છે.',
    'why.card3.title': 'સામાજિક સુરક્ષા અને વીમો',
    'why.card3.desc': 'અકસ્માત વીમો અને આરોગ્ય સુવિધાઓમાં આપમેળે નોંધણી.',
    'cta.title': 'વિશ્વસનીય સહકારી સેવાનો લાભ લેવા તૈયાર છો?',
    'cta.desc': '2 મિનિટમાં ટેકનિશિયન બુક કરો અથવા તમારી મંડળી નોંધાવો.',
    'cta.bookNow': 'હમણાં બુક કરો',
    'cta.register': 'મંડળી નોંધાવો',
    'matching.aiTitle': 'સહાયક AI — કારીગર ભલામણ સલાહકાર',
    'matching.deterministicBadge': 'પારદર્શક સ્કોરિંગ પદ્ધતિ',
    'matching.proximity': 'ભૌગોલિક નિકટતા (40%)',
    'matching.rating': 'અનુભવ અને રેટિંગ (25%)',
    'matching.certification': 'NSQF કૌશલ્ય પ્રમાણપત્ર (20%)',
    'matching.rotation': 'સમાન તક રોટેશન (15%)',
    'matching.dispatch': 'કારીગર મોકલો',
    'matching.verifiedArtisan': 'ચકાસાયેલ સહકારી સભ્ય',
    'status.verifiedSession': 'ચકાસાયેલ સહકારી સત્ર',
    'chat.placeholder': 'તમને જોઈતી સેવાનું વર્ણન કરો...',
    'chat.send': 'મોકલો',
    'chat.assistantGreeting': 'નમસ્તે! હું સહાયક AI છું. તમારી સેવાની જરૂરિયાત મને જણાવો.',
  },
};

// Comprehensive cross-page phrase translations for live DOM replacement
const PHRASE_DICTIONARIES: Record<SupportedLanguage, Record<string, string>> = {
  en: {},
  hi: {
    'How BharatGig Works': 'भारतगिग कैसे काम करता है',
    'Choose Service & Location': 'सेवा और स्थान चुनें',
    'Direct Dispatch & Work Completion': 'सीधा प्रेषण और कार्य पूर्णता',
    '100% Direct Payout & Welfare': '100% सीधा भुगतान और कल्याण',
    'Select your required household service and schedule. Our PostGIS engine matches you with verified guild artisans nearest to your GPS coordinates.':
      'अपनी आवश्यक घरेलू सेवा और समय चुनें। हमारा PostGIS इंजन आपके जीपीएस निर्देशांक के निकटतम सत्यापित सहकारी कारीगरों से आपको जोड़ता है।',
    'The artisan arrives on site, performs the diagnosis, and completes the work under standard cooperative quality and transparent pricing guidelines.':
      'कारीगर साइट पर पहुंचता है, जांच करता है और मानक सहकारी गुणवत्ता व पारदर्शी मूल्य निर्धारण के तहत काम पूरा करता है।',
    'Pay digitally via UPI. The artisan receives 100% of their standard labour wage with automatic contribution to accident and health welfare funds.':
      'यूपीआई द्वारा डिजिटल भुगतान करें। कारीगर को दुर्घटना और स्वास्थ्य कल्याण कोष में योगदान के साथ उनका 100% श्रम वेतन मिलता है।',
    'Transparent & Simple': 'पारदर्शी और सरल',
    'A community-driven lifecycle that protects both the household and the working artisan.':
      'एक समुदाय-संचालित प्रणाली जो परिवार और कामकाजी कारीगर दोनों की सुरक्षा करती है।',
    'Platform Hierarchy & Role Desks': 'प्लेटफ़ॉर्म पदानुक्रम और भूमिका डेस्क',
    'Access Dedicated Portals': 'समर्पित पोर्टल तक पहुंचें',
    'Household Portal': 'घरेलू पोर्टल',
    'Customer Hub': 'ग्राहक हब',
    'Artisan Portal': 'कारीगर पोर्टल',
    'Worker Desk': 'कारीगर डेस्क',
    'Cooperative Branch': 'सहकारी शाखा',
    'Society Operations': 'सोसायटी संचालन',
    'State Apex': 'राज्य शीर्ष निकाय',
    'Federation Apex': 'महासंघ एपेक्स',
    'Enter Portal': 'पोर्टल में प्रवेश करें',
    'Fair Wage Band': 'उचित वेतन सीमा',
    'Book': 'बुक करें',
    'Certified Electrician': 'प्रमाणित इलेक्ट्रीशियन',
    'Master Plumber': 'मास्टर प्लंबर',
    'Sanitation & Deep Cleaning': 'स्वच्छता और गहरी सफाई',
    'Elderly & Nursing Caregiver': 'बुजुर्ग और नर्सिंग देखभालकर्ता',
    'Wiring, circuit breakers, emergency short-circuits': 'वायरिंग, सर्किट ब्रेकर, शॉर्ट सर्किट मरम्मत',
    'Pipe leaks, drainage, fixture repairs, water tanks': 'पाइप रिसाव, जल निकासी, नल व टंकी मरम्मत',
    'Full-house sanitization, kitchen/bath deep scrub': 'पूरे घर का सैनिटाइजेशन, रसोई व बाथरूम सफाई',
    'Compassionate assistance, mobility support, bedside care': 'देखभाल सहायता, गतिशीलता समर्थन, सेवा',
    'Services': 'सेवाएं',
    'Ecosystem': 'पारिस्थितिकी तंत्र',
    'Portals': 'पोर्टल्स',
    'Electrician Services': 'इलेक्ट्रीशियन सेवाएं',
    'Plumbing & Sanitary': 'प्लंबिंग और स्वच्छता',
    'Deep Cleaning': 'गहरी सफाई सेवा',
    'Elder & Patient Care': 'बुजुर्ग व रोगी देखभाल',
    'Emergency Dispatch': 'आपातकालीन प्रेषण',
    'For Skilled Workers': 'कुशल कामगारों के लिए',
    'For Cooperative Societies': 'सहकारी समितियों के लिए',
    'How It Works': 'यह कैसे काम करता है',
    'Cooperative Bylaws': 'सहकारी उप-नियम',
    'Role Switcher / Sign In': 'भूमिका बदलें / साइन इन',
    'Multi-Tenant Cooperative Federation Architecture': 'मल्टी-टेनेंट सहकारी महासंघ वास्तुकला',
    '0% Middleman Cut': '0% बिचौलिया कटौती',
    'DPDPA 2023 Compliant': 'DPDPA 2023 अनुपालन',
    'PostGIS Dispatch': 'PostGIS जीपीएस प्रेषण',
    'Cooperative-owned public digital infrastructure.': 'सहकारी स्वामित्व वाला सार्वजनिक डिजिटल बुनियादी ढांचा।',
    'Household Service Hub': 'घरेलू सेवा हब',
    'Manage your home service requests, live artisan tracking, and cooperative receipts.': 'अपने सेवा अनुरोध, लाइव कारीगर ट्रैकिंग और रसीदें प्रबंधित करें।',
    'My Service Bookings': 'मेरी सेवा बुकिंग',
    'View ongoing dispatches, past receipts, and artisan track records.': 'चल रहे प्रेषण, पुरानी रसीदें और कारीगर का रिकॉर्ड देखें।',
    'Active Dispatches': 'सक्रिय प्रेषण',
    'Completed Services': 'पूर्ण सेवाएं',
    'Direct Artisan Payouts': 'कारीगरों को सीधा भुगतान',
    'Active Dispatch': 'सक्रिय प्रेषण',
    'Assigned Artisan': 'नियुक्त कारीगर',
    'Standard Cost': 'मानक लागत',
    'Live GPS Tracking': 'लाइव जीपीएस ट्रैकिंग',
    'Track GPS': 'जीपीएस ट्रैक करें',
    'Invoice': 'चालान / रसीद',
    'Rate Service': 'रेटिंग दें',
    'Booking ID': 'बुकिंग आईडी',
    'Service & Category': 'सेवा और श्रेणी',
    'Schedule & Location': 'समय और स्थान',
    'Amount': 'राशि',
    'Status': 'स्थिति',
    'Actions': 'कार्रवाई',
    'All Bookings': 'सभी बुकिंग',
    'Book New Service': 'नई सेवा बुक करें',
    'Back to My Bookings': 'मेरी बुकिंग पर वापस जाएं',
    'Back to Services': 'सेवाओं पर वापस जाएं',
    'Live GPS Radar Active': 'लाइव जीपीएस रडार सक्रिय',
    'Estimated Arrival': 'अनुमानित आगमन',
    'Service Lifecycle Status': 'सेवा जीवन चक्र स्थिति',
    'Requested': 'अनुरोधित',
    'Assigned': 'नियुक्त',
    'On The Way': 'रास्ते में है',
    'In Progress': 'प्रगति पर है',
    'Completed': 'पूर्ण हुआ',
    'Mark Artisan Arrived': 'कारीगर आगमन चिह्नित करें',
    'Finish & Settle Payment': 'कार्य समाप्त करें और भुगतान करें',
    'Call Artisan': 'कारीगर को कॉल करें',
    'Message': 'संदेश भेजें',
    'Pay with Razorpay': 'रेज़रपे से भुगतान करें',
    'Cooperative Backed': 'सहकारी समर्थित',
  },
  kn: {
    'How BharatGig Works': 'ಭಾರತಗಿಗ್ ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ',
    'Choose Service & Location': 'ಸೇವೆ ಮತ್ತು ಸ್ಥಳವನ್ನು ಆರಿಸಿ',
    'Direct Dispatch & Work Completion': 'ನೇರ ನಿಯೋಜನೆ ಮತ್ತು ಕೆಲಸ ಪೂರ್ಣಗೊಳಿಸುವಿಕೆ',
    '100% Direct Payout & Welfare': '100% ನೇರ ಪಾವತಿ ಮತ್ತು ಕಲ್ಯಾಣ',
    'Transparent & Simple': 'ಪಾರದರ್ಶಕ ಮತ್ತು ಸರಳ',
    'Platform Hierarchy & Role Desks': 'ವೇದಿಕೆಯ ಶ್ರೇಣಿ ಮತ್ತು ಪಾತ್ರ ಡೆಸ್ಕ್‌ಗಳು',
    'Access Dedicated Portals': 'ಮೀಸಲಾದ ಪೋರ್ಟಲ್‌ಗಳಿಗೆ ಪ್ರವೇಶಿಸಿ',
    'Household Portal': 'ಗೃಹ ಪೋರ್ಟಲ್',
    'Customer Hub': 'ಗ್ರಾಹಕರ ಹಬ್',
    'Artisan Portal': 'ಕುಶಲಕರ್ಮಿ ಪೋರ್ಟಲ್',
    'Worker Desk': 'ಕೆಲಸಗಾರರ ಡೆಸ್ಕ್',
    'Cooperative Branch': 'ಸಹಕಾರಿ ಶಾಖೆ',
    'Society Operations': 'ಸಂಘದ ಕಾರ್ಯಾಚರಣೆಗಳು',
    'State Apex': 'ರಾಜ್ಯ ಅಪೆಕ್ಸ್',
    'Federation Apex': 'ಒಕ್ಕೂಟದ ಅಪೆಕ್ಸ್',
    'Enter Portal': 'ಪೋರ್ಟಲ್ ಪ್ರವೇಶಿಸಿ',
    'Fair Wage Band': 'ನ್ಯಾಯಯುತ ಕೂಲಿ ದರ',
    'Book': 'ಬುಕ್ ಮಾಡಿ',
    'Certified Electrician': 'ಪ್ರಮಾಣೀಕೃತ ಎಲೆಕ್ಟ್ರಿಷಿಯನ್',
    'Master Plumber': 'ಮಾಸ್ಟರ್ ಪ್ಲಂಬರ್',
    'Sanitation & Deep Cleaning': 'ನೈರ್ಮಲ್ಯ ಮತ್ತು ಆಳವಾದ ಶುಚಿಗೊಳಿಸುವಿಕೆ',
    'Elderly & Nursing Caregiver': 'ಹಿರಿಯರು ಮತ್ತು ನರ್ಸಿಂಗ್ ಆರೈಕೆದಾರರು',
    'Services': 'ಸೇವೆಗಳು',
    'Ecosystem': 'ಪರಿಸರ ವ್ಯವಸ್ಥೆ',
    'Portals': 'ಪೋರ್ಟಲ್‌ಗಳು',
    'Electrician Services': 'ವಿದ್ಯುತ್ ಸೇವೆಗಳು',
    'Plumbing & Sanitary': 'ಪ್ಲಂಬಿಂಗ್ ಮತ್ತು ನೈರ್ಮಲ್ಯ',
    'Deep Cleaning': 'ಆಳವಾದ ಶುಚಿಗೊಳಿಸುವಿಕೆ',
    'Elder & Patient Care': 'ಹಿರಿಯರ ಆರೈಕೆ',
    'Emergency Dispatch': 'ತುರ್ತು ನಿಯೋಜನೆ',
    'Household Service Hub': 'ಗೃಹ ಸೇವಾ ಕೇಂದ್ರ',
    'My Service Bookings': 'ನನ್ನ ಸೇವಾ ಬುಕಿಂಗ್‌ಗಳು',
    'Active Dispatches': 'ಸಕ್ರಿಯ ನಿಯೋಜನೆಗಳು',
    'Completed Services': 'ಪೂರ್ಣಗೊಂಡ ಸೇವೆಗಳು',
    'Direct Artisan Payouts': 'ಕುಶಲಕರ್ಮಿಗಳಿಗೆ ನೇರ ಪಾವತಿ',
    'Live GPS Tracking': 'ಲೈವ್ ಜಿಪಿಎಸ್ ಟ್ರ್ಯಾಕಿಂಗ್',
    'Track GPS': 'ಜಿಪಿಎಸ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    'Invoice': 'ರಶೀದಿ',
    'Rate Service': 'ರೇಟಿಂಗ್ ನೀಡಿ',
    'Booking ID': 'ಬುಕಿಂಗ್ ಐಡಿ',
    'Amount': 'ಮೊತ್ತ',
    'Status': 'ಸ್ಥಿತಿ',
    'Actions': 'ಕ್ರಮಗಳು',
    'Book New Service': 'ಹೊಸ ಸೇವೆ ಬುಕ್ ಮಾಡಿ',
    'Live GPS Radar Active': 'ಲೈವ್ ಜಿಪಿಎಸ್ ರಾಡಾರ್ ಸಕ್ರಿಯ',
    'Estimated Arrival': 'ಅಂದಾಜು ಆಗಮನ',
    'Requested': 'ವಿನಂತಿಸಲಾಗಿದೆ',
    'Assigned': 'ನಿಯೋಜಿಸಲಾಗಿದೆ',
    'On The Way': 'ದಾರಿಯಲ್ಲಿದ್ದಾರೆ',
    'In Progress': 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    'Completed': 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    'Call Artisan': 'ಕರೆ ಮಾಡಿ',
    'Message': 'ಸಂದೇಶ',
    'Pay with Razorpay': 'ರೇಜರ್‌ಪೇ ಮೂಲಕ ಪಾವತಿಸಿ',
  },
  ta: {
    'How BharatGig Works': 'பாரத்கிக் எப்படி செயல்படுகிறது',
    'Choose Service & Location': 'சேவை மற்றும் இருப்பிடத்தைத் தேர்ந்தெடுக்கவும்',
    'Direct Dispatch & Work Completion': 'நேரடி அனுப்புதல் & பணி முடித்தல்',
    '100% Direct Payout & Welfare': '100% நேரடி ஊதியம் & நலன்புரி',
    'Transparent & Simple': 'வெளிப்படையான மற்றும் எளிய முறை',
    'Platform Hierarchy & Role Desks': 'தள படிநிலை & பயனர் போர்ட்டல்கள்',
    'Access Dedicated Portals': 'போர்ட்டலை அணுகவும்',
    'Household Portal': 'வீட்டு போர்ட்டல்',
    'Customer Hub': 'வாடிக்கையாளர் மையம்',
    'Artisan Portal': 'தொழிலாளர் போர்ட்டல்',
    'Worker Desk': 'பணியாளர் மையம்',
    'Cooperative Branch': 'கூட்டுறவு கிளை',
    'Society Operations': 'சங்க நடவடிக்கைகள்',
    'State Apex': 'மாநில தலைமை',
    'Federation Apex': 'கூட்டமைப்பு தலைமை',
    'Enter Portal': 'உள்நுழைக',
    'Fair Wage Band': 'நியாயமான ஊதிய வரம்பு',
    'Book': 'முன்பதிவு',
    'Certified Electrician': 'சான்றளிக்கப்பட்ட எலக்ட்ரீஷியன்',
    'Master Plumber': 'முதன்மை பிளம்பர்',
    'Sanitation & Deep Cleaning': 'துப்புரவு & ஆழமான சுத்தம்',
    'Elderly & Nursing Caregiver': 'முதியோர் பராமரிப்பாளர்',
    'Services': 'சேவைகள்',
    'Ecosystem': 'சூழல்',
    'Portals': 'தளங்கள்',
    'Live GPS Tracking': 'நேரலை ஜிபிஎஸ் கண்காணிப்பு',
    'Track GPS': 'ஜிபிஎஸ் கண்காணிக்க',
    'Invoice': 'விலைப்பட்டியல்',
    'Amount': 'தொகை',
    'Status': 'நிலை',
    'Book New Service': 'புதிய சேவையை முன்பதிவு செய்க',
    'On The Way': 'வழியில் உள்ளார்',
    'In Progress': 'நடைபெறுகிறது',
    'Completed': 'முடிந்தது',
    'Call Artisan': 'தொலைபேசி அழைப்பு',
    'Pay with Razorpay': 'ரேஸர்பே மூலம் செலுத்துக',
  },
  te: {
    'How BharatGig Works': 'భారత్‌గిగ్ ఎలా పనిచేస్తుంది',
    'Choose Service & Location': 'సేవ మరియు స్థానాన్ని ఎంచుకోండి',
    'Direct Dispatch & Work Completion': 'ప్రత్యక్ష కేటాయింపు & పని పూర్తి',
    '100% Direct Payout & Welfare': '100% ప్రత్యక్ష చెల్లింపు & సంక్షేమం',
    'Platform Hierarchy & Role Desks': 'ప్లాట్‌ఫారమ్ సోపానక్రమం & పోర్టల్స్',
    'Household Portal': 'గృహ పోర్టల్',
    'Customer Hub': 'కస్టమర్ హబ్',
    'Artisan Portal': 'కార్మిక పోర్టల్',
    'Worker Desk': 'కార్మికుల డెస్క్',
    'Enter Portal': 'పోర్టల్ ప్రవేశించండి',
    'Fair Wage Band': 'సరైన వేతన శ్రేణి',
    'Book': 'బుక్ చేయండి',
    'Certified Electrician': 'సర్టిఫైడ్ ఎలక్ట్రీషియన్',
    'Master Plumber': 'మాస్టర్ ప్లంబర్',
    'Sanitation & Deep Cleaning': 'పారిశుధ్యం & డీప్ క్లీనింగ్',
    'Elderly & Nursing Caregiver': 'వృద్ధుల సంరక్షకుడు',
    'Live GPS Tracking': 'లైవ్ జీపీఎస్ ట్రాకింగ్',
    'Track GPS': 'జీపీఎస్ ట్రాక్ చేయండి',
    'Invoice': 'రసీదు',
    'Amount': 'మొత్తం',
    'Status': 'స్థితి',
    'Book New Service': 'కొత్త సేవ బుక్ చేయండి',
    'On The Way': 'దారిలో ఉన్నారు',
    'In Progress': 'పురోగతిలో ఉంది',
    'Completed': 'పూర్తయింది',
    'Call Artisan': 'కాల్ చేయండి',
    'Pay with Razorpay': 'రేజర్‌పేతో చెల్లించండి',
  },
  mr: {
    'How BharatGig Works': 'भारतगिग कसे कार्य करते',
    'Choose Service & Location': 'सेवा आणि स्थान निवडा',
    'Direct Dispatch & Work Completion': 'थेट नियुक्ती आणि काम पूर्ण',
    '100% Direct Payout & Welfare': '100% थेट मोबदला आणि कल्याण',
    'Platform Hierarchy & Role Desks': 'प्लॅटफॉर्म पदानुक्रम आणि भूमिका डेस्क',
    'Household Portal': 'घरगुती पोर्टल',
    'Customer Hub': 'ग्राहक केंद्र',
    'Artisan Portal': 'कारागीर पोर्टल',
    'Worker Desk': 'कामगार डेस्क',
    'Enter Portal': 'पोर्टल उघडा',
    'Fair Wage Band': 'योग्य वेतन श्रेणी',
    'Book': 'बुक करा',
    'Certified Electrician': 'प्रमाणित इलेक्ट्रिशियन',
    'Master Plumber': 'मास्टर प्लंबर',
    'Sanitation & Deep Cleaning': 'स्वच्छता आणि डीप क्लीनिंग',
    'Elderly & Nursing Caregiver': 'वृद्धांची काळजीवाहक',
    'Live GPS Tracking': 'थेट जीपीएस ट्रॅकिंग',
    'Track GPS': 'जीपीएस ट्रॅक करा',
    'Invoice': 'पावती',
    'Amount': 'रक्कम',
    'Status': 'स्थिती',
    'Book New Service': 'नवीन सेवा बुक करा',
    'On The Way': 'वाटेवर आहे',
    'In Progress': 'काम सुरू आहे',
    'Completed': 'पूर्ण झाले',
    'Call Artisan': 'कॉल करा',
    'Pay with Razorpay': 'रेझरपेने पैसे द्या',
  },
  bn: {
    'How BharatGig Works': 'ভারতগিগ কীভাবে কাজ করে',
    'Choose Service & Location': 'পরিষেবা এবং অবস্থান নির্বাচন করুন',
    'Direct Dispatch & Work Completion': 'সরাসরি প্রেরণ এবং কাজ সমাপ্তি',
    '100% Direct Payout & Welfare': '১০০% সরাসরি মজুরি ও কল্যাণ',
    'Platform Hierarchy & Role Desks': 'প্ল্যাটফর্ম অনুক্রম এবং ভূমিকা ডেস্ক',
    'Household Portal': 'গৃহস্থালি পোর্টাল',
    'Customer Hub': 'গ্রাহক কেন্দ্র',
    'Artisan Portal': 'কারিগর পোর্টাল',
    'Worker Desk': 'শ্রমিক ডেস্ক',
    'Enter Portal': 'প্রবেশ করুন',
    'Fair Wage Band': 'ন্যায্য মজুরি বন্ধনী',
    'Book': 'বুক করুন',
    'Certified Electrician': 'প্রত্যয়িত ইলেকট্রিশিয়ান',
    'Master Plumber': 'মাস্টার প্লাম্বার',
    'Sanitation & Deep Cleaning': 'পরিচ্ছন্নতা ও গভীর পরিষ্কার',
    'Elderly & Nursing Caregiver': 'বয়স্ক সেবা প্রদানকারী',
    'Live GPS Tracking': 'লাইভ জিপিএস ট্র্যাকিং',
    'Track GPS': 'ট্র্যাক করুন',
    'Invoice': 'রসিদ',
    'Amount': 'পরিমাণ',
    'Status': 'স্থিতি',
    'Book New Service': 'নতুন সেবা বুক করুন',
    'On The Way': 'পথিমধ্যে',
    'In Progress': 'চলমান',
    'Completed': 'সম্পন্ন',
    'Call Artisan': 'কল করুন',
    'Pay with Razorpay': 'রেজারপে দিয়ে দিন',
  },
  gu: {
    'How BharatGig Works': 'ભારતગીગ કેવી રીતે કાર્ય કરે છે',
    'Choose Service & Location': 'સેવા અને સ્થળ પસંદ કરો',
    'Direct Dispatch & Work Completion': 'સીધી ફાળવણી અને કામ પૂર્ણતા',
    '100% Direct Payout & Welfare': '100% સીધું વેતન અને કલ્યાણ',
    'Platform Hierarchy & Role Desks': 'પ્લેટફોર્મ ડેસ્ક અને ભૂમિકાઓ',
    'Household Portal': 'ઘરગથ્થુ પોર્ટલ',
    'Customer Hub': 'ગ્રાહક હબ',
    'Artisan Portal': 'કારીગર પોર્ટલ',
    'Worker Desk': 'કારીગર ડેસ્ક',
    'Enter Portal': 'દાખલ થાઓ',
    'Fair Wage Band': 'યોગ્ય વેતન શ્રેણી',
    'Book': 'બુક કરો',
    'Certified Electrician': 'પ્રમાણિત ઇલેક્ટ્રિશિયન',
    'Master Plumber': 'માસ્ટર પ્લમ્બર',
    'Sanitation & Deep Cleaning': 'સ્વચ્છતા અને ડીપ ક્લિનિંગ',
    'Elderly & Nursing Caregiver': 'વૃદ્ધ દર્દી સંભાળનાર',
    'Live GPS Tracking': 'લાઇવ જીપીએસ ટ્રેકિંગ',
    'Track GPS': 'જીપીએસ ટ્રેક કરો',
    'Invoice': 'બીલ',
    'Amount': 'રકમ',
    'Status': 'સ્થિતિ',
    'Book New Service': 'નવી સેવા બુક કરો',
    'On The Way': 'રસ્તામાં છે',
    'In Progress': 'કામ ચાલુ છે',
    'Completed': 'પૂર્ણ થયું',
    'Call Artisan': 'કોલ કરો',
    'Pay with Razorpay': 'રેઝરપેથી ચૂકવો',
  },
};

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
  languages: LanguageInfo[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<SupportedLanguage>('en');

  useEffect(() => {
    try {
      const saved = localStorage.getItem('bharatgig_language') as SupportedLanguage;
      if (saved && TRANSLATIONS[saved]) {
        setLanguageState(saved);
      }
    } catch {
      // LocalStorage unavailable
    }
  }, []);

  const setLanguage = (lang: SupportedLanguage) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('bharatgig_language', lang);
    } catch {
      // LocalStorage unavailable
    }
  };

  const t = (key: string): string => {
    const currentDict = TRANSLATIONS[language] || TRANSLATIONS.en;
    if (currentDict[key]) {
      return currentDict[key];
    }
    return TRANSLATIONS.en[key] || key;
  };

  // Live DOM Mutation and Text-Node Translation Engine
  useEffect(() => {
    if (typeof window === 'undefined') return;

    const dict = PHRASE_DICTIONARIES[language];

    // Function to translate or revert a tree of nodes
    const applyTranslation = (root: Node) => {
      const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
        acceptNode: (node) => {
          const parent = node.parentElement;
          if (!parent) return NodeFilter.FILTER_REJECT;
          const tag = parent.tagName.toLowerCase();
          if (['script', 'style', 'noscript', 'textarea', 'input', 'code', 'pre'].includes(tag)) {
            return NodeFilter.FILTER_REJECT;
          }
          if (parent.closest('[data-no-translate]')) {
            return NodeFilter.FILTER_REJECT;
          }
          const text = node.nodeValue?.trim();
          return text && text.length > 0 ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT;
        },
      });

      let currentNode = walker.nextNode();
      while (currentNode) {
        const textNode = currentNode as Text;
        const parent = textNode.parentElement;
        if (parent) {
          // Keep original text on the node if not yet stored
          if ((textNode as any).__origText === undefined) {
            (textNode as any).__origText = textNode.nodeValue || '';
          }

          const originalText = (textNode as any).__origText;

          if (language === 'en' || !dict) {
            textNode.nodeValue = originalText;
          } else {
            const trimmed = originalText.trim();
            if (dict[trimmed]) {
              textNode.nodeValue = originalText.replace(trimmed, dict[trimmed]);
            } else {
              // Check if any known phrase matches a substring
              let replaced = originalText;
              for (const [enPhrase, localized] of Object.entries(dict)) {
                if (enPhrase.length > 3 && replaced.includes(enPhrase)) {
                  replaced = replaced.split(enPhrase).join(localized);
                }
              }
              if (replaced !== originalText) {
                textNode.nodeValue = replaced;
              }
            }
          }
        }
        currentNode = walker.nextNode();
      }
    };

    // Apply immediately to existing document body
    applyTranslation(document.body);

    // Observe changes so dynamically loaded routes & cards translate automatically
    const observer = new MutationObserver((mutations) => {
      for (const mutation of mutations) {
        for (const node of Array.from(mutation.addedNodes)) {
          applyTranslation(node);
        }
      }
    });

    observer.observe(document.body, { childList: true, subtree: true });

    return () => {
      observer.disconnect();
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages: SUPPORTED_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
